apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-capstone-green

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: kubernetes-capstone-green
          image: austinmeyer/udacity_aws_cloud_devops_capstone_green
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080