apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-green

spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-devops-capstone-green
  template:
    metadata:
      labels:
        app: udacity-devops-capstone-green
    spec:
      containers:
        - name: udacity-devops-capstone-green
          image: austinmeyer/udacity-devops-capstone-green:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080