apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-green
  labels:
    app: udacity-devops-capstone-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-devops-capstone-green
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devops-capstone-green
    spec:
      containers:
        - image: austinmeyer/udacity-devops-capstone-green:latest
          imagePullPolicy: Always
          name: udacity-devops-capstone-green
          ports:
            - containerPort: 80