apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-green
  labels:
    app: udacity-devops-capstone-green
spec:
  type: LoadBalancer
  selector:
    app: udacity-devops-capstone-green
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP