apiVersion: apps/v1
kind: Deployment
metadata:
  name: Kubernetes-Capstone-blue

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: Kubernetes-Capstone-blue
          image: austinmeyer/udacity_aws_cloud_devops_capstone_blue
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
