apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-capstone-blue

spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-capstone-blue
  template:
    metadata:
      labels:
        app: kubernetes-capstone-blue
    spec:
      containers:
        - name: kubernetes-capstone-blue
          image: austinmeyer/udacity-devops-capstone-blue
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
