apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone
  labels:
    app: udacity-devops-capstone-blue
spec:
  type: LoadBalancer
  selector:
    app: udacity-devops-capstone-blue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP